### PR TITLE
Maintenance update

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
The PR does not contain any functional updates. Roughly summarized, these are updates, typos and format harmonization.

See the commits for details.

Thanks for this nice module! :slightly_smiling_face:

### CODE REVIEW

**Comment by nkl-kst** [comment]
Thanks @KristjanESPERANTO for this PR and your work! There are many and I don't think it's necessary to change all these formatting aspects. Could you try to find a Prettier configuration that doesn't result in so many changes?

E.g. trailing comma in objets/arrays should be mandatory. There should be no whitespace after the `function`-keyword. No blank lines after function opening and so on.

**Comment by KristjanESPERANTO** [comment]
- [x] trailing comma: I changed it.
- [ ] no whitespace after the function-keyword: Seems that there is no option to disable this: <https://github.com/prettier/prettier/issues/11148>.
- [ ] No blank lines after function opening: I can't find an option for that either.

I know it's a bit difficult to keep track of the changes when there are so many in one PR. Sorry for that.

**Comment by nkl-kst** [comment]
I read about Prettier and found out that it is "opinionated" with very few options. I think that's reasonable as "the biggest reason for adopting Prettier is to stop all the on-going debates over styles". Sounds good.

I'd like to honor your work and therefore stop the discussion about whitespaces and blank lines to accept this PR, but there are two more things that are important for me:

1. We should add Prettier to the GitHub workflow
2. Is it possible to split arrays over multiple lines, even if they have just one element (eg. in [getScripts](https://github.com/nkl-kst/MMM-OnThisDay/pull/27/files#diff-70cf5ed2cf0ef265d498ac7e62ca08c299b9306fe56c9022b756f28ec04b28c7R41-R42) and [getStyles](https://github.com/nkl-kst/MMM-OnThisDay/pull/27/files#diff-70cf5ed2cf0ef265d498ac7e62ca08c299b9306fe56c9022b756f28ec04b28c7R50-R51))? I really like small diffs and this would improve the readability for changes when adding/removing array elements.

Thanks again for your work! In the last years I was busy with other things, but may I should also spend some time to improve this module, as it seems to be useful for some people :)

**Comment by KristjanESPERANTO** [comment]
1. Yes, that makes sense, I have done a similar thing in other projects in combination with `husky` and `eslint`. To avoid overloading this PR even more, I would tackle this in another PR. Or what do you think?
2. I added `// prettier-ignore` to preserve the array format. I found no better option.

**Comment by nkl-kst** [comment]
Tested on my mirror and works like a charm! Thank you very much @KristjanESPERANTO 👏

**Comment by KristjanESPERANTO** [comment]
You're welcome!

BTW, MMM-OnThisDay is now displayed very well on the [module page](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) that I am building.

**Pull request merged**
